{
 "title": "Mi API go-api-chi",
 "description": "go-goroutines",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Estado del Runtime (Go & Sistema)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total de peticiones",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "promhttp_metric_handler_requests_total",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Goroutines Activas",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      { "expr": "go_goroutines", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Memoria Ram",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "go_memstats_alloc_bytes", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Métricas de Aplicación (Método RED)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Salud de la API (Errores)",
     "type": "bargauge",
     "description": "Muestra la cantidad de peticiones fallidas por segundo, agrupadas por ruta y código de estado HTTP.\"",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(http_requests_total{status=~\"4..|5..\"}[1m])) by (endpoint, status)",
       "legendFormat": "{{endpoint}} ({{status}})"
      }
     ]
    },
    {
     "title": "Latencia de Endpoints (P95)",
     "type": "timeseries",
     "description": "Este gráfico muestra el tiempo de respuesta (en segundos) que experimenta el 95% de los usuarios para cada ruta de la API. Permite identificar cuellos de botella y lentitud en endpoints específicos como /productos o /login.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (le, endpoint))",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "title": "Usuarios Concurrentes",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "http_requests_in_flight", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}